### ISSUE TITLE
Extract the file tree from the commit

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Fenrir#10]
We'll need a function that takes a commit data and extracts the full file tree from it.

Depends on: #5.

**Comment by ruthenium96** [comment]
Мы уже умеем парсить коммиты (в типе `CommitBody` есть поле `Tree : String`). Я так понимаю, необходимо реализовать структуру, соответствующую распарсенному tree файлу? В нём будет находиться вся необходимая информация: хэши его файлов и хэши его поддеревьев, при необходимости по ним можно получать доступ к самим файлам и поддеревьям.

**Comment by ForNeVeR** [comment]
Да, всё верно.
