### ISSUE TITLE
Extract and save particular file contents

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Fenrir#12]
We'll need a function that takes an object id and a file path, and outputs a stream with raw contents of that file (to be saved onto disk or whatever).

Depends on #5.

**Comment by ruthenium96** [comment]
Что в данном случае id, а что file path? id -- это тот хэш, под которым хранятся эти файлы в гите?

**Comment by ForNeVeR** [comment]
id — это идентификатор блоба, а file path — это путь, куда сохранить raw-блоб на диск.
