### ISSUE TITLE
Update refs

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Fenrir#16]
We'll need a function that takes an ref and a commit id, and updates a ref to point to a new commit id.

**Comment by ruthenium96** [comment]
Is it good idea to check .git/HEAD to find name of current branch? Can it causes problems with detached head state?

Git keep history of commits in .git/logs/, does git use it for `git log`?

**Comment by ForNeVeR** [comment]
> Is it good idea to check .git/HEAD to find name of current branch?

Yes, it is a good idea. But please keep in mind, that we only use **current branch** as default choice; there should definitely be an ability for the user to override ref of their choice.

> Can it causes problems with detached head state?

Good catch! Fenrir's main operation mode could destroy current state if the repository is in detached state and we modify `HEAD`. So, it's a good idea to detect detached state and require `--force` flag to overwrite `HEAD` if it's in the detached state.

But anyway, everything (including commits made in a detached state) should still be available via `git log --reflog` even after Fenrir destroys something, so it's not a big deal.

> Git keep history of commits in .git/logs/, does git use it for `git log`?

Unfortunately, I'm not yet familiar with `.git/logs`, will take a look a bit later.

**Comment by ForNeVeR** [comment]
According to the blog post I found, `.git/logs` contain data used for reflog only, and it is possible to clean it up when you want.

For example, after `git clone`, my `.git/logs/HEAD` file contains only one line:
```
0000000000000000000000000000000000000000 f091f85b8b09cb1813cfbeb8bcbdf2870e46ad36 Friedrich von Never <friedrich@fornever.me> 1590242713 +0700  clone: from git@github.com:ForNeVeR/Fenrir.git
```

Ideally, we should modify this reflog on performing any repo operations.

**Comment by ForNeVeR** [comment]
1. `update-ref <ref name> <commit id>`
2. Integrate this command with `update-commit`
