### ISSUE TITLE
HEAD file contents instead of hash in parseCommitBody

### ISSUE THREAD

**Issue by Daniel-mon-Goose** [ForNeVeR/Fenrir#39]
Trying to access refs/remotes/origin/HEAD in UI Refs windows results in passing HEAD file contents instead of any commit hash
![image](https://user-images.githubusercontent.com/49589429/87788846-80fd1100-c857-11ea-90f1-264ba70e360c.png)

**Comment by ForNeVeR** [comment]
Fixed by #60.
